# Generated by Django 4.0.3 on 2022-04-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation', models.CharField(max_length=150, unique=True)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('flat', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('net_income', models.IntegerField()),
            ],
        ),
    ]
